version: '3.8'

services:
  webhook:
    # Build from source
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Core Configuration
      NODE_ENV: production
      PORT: 3002
      TRUST_PROXY: "true"
      WEBHOOK_URL: https://claude.perfux.dev
      
      # Authentication
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      CLAUDE_API_SECRET: ${CLAUDE_API_SECRET}
      
      # Bot Configuration
      BOT_USERNAME: ${BOT_USERNAME:-@ClaudeEistrach}
      BOT_EMAIL: ${BOT_EMAIL:-eugeneistrach@gmail.com}
      AUTHORIZED_USERS: ${AUTHORIZED_USERS:-eugeneistrach,EugenEistrach}
      DEFAULT_GITHUB_OWNER: ${DEFAULT_GITHUB_OWNER:-eugeneistrach}
      DEFAULT_AUTHORIZED_USER: ${DEFAULT_AUTHORIZED_USER:-eugeneistrach}
      
      # Disable container mode for now
      CLAUDE_USE_CONTAINERS: "0"
      
      # Discord Integration (optional)
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      DISCORD_AUTHORIZED_USERS: ${DISCORD_AUTHORIZED_USERS}
      
      # Claude Trace
      ENABLE_CLAUDE_TRACE: ${ENABLE_CLAUDE_TRACE:-true}
      CLAUDE_SESSIONS_RETENTION_DAYS: ${CLAUDE_SESSIONS_RETENTION_DAYS:-7}
    ports:
      - "3002"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "dokploy.enabled=true"
      - "traefik.enable=true"
      - "traefik.http.routers.claude-webhook.rule=Host(`claude.perfux.dev`)"
      - "traefik.http.routers.claude-webhook.entrypoints=websecure"
      - "traefik.http.routers.claude-webhook.tls.certResolver=letsencrypt"
      - "traefik.http.services.claude-webhook.loadbalancer.server.port=3002"

networks:
  dokploy-network:
    external: true